### ISSUE TITLE
Operator: Concurrent downloads bug

### ISSUE THREAD

**Issue by juliangruber** [optoolco/beta#20] opened 2021-01-12 11:31 UTC
If you download multiple apps at the same time, only one will get the "Launch" button, the others need to be downloaded again.

**Comment by Raynos** [comment] 2021-01-13 10:38
When I press download it will launch after downloading, if i download 2/3 apps at the same time it launches all three.

Did you get shown the activation key page after pressing launch/download ? 

After you enter an activation key you will have to go back to the apps and download them again.

**Comment by juliangruber** [comment] 2021-01-13 10:40
I did not get shown the activation key page by the app(s), I needed to manually enter it. That explains why I needed to download them again I think

**Comment by Raynos** [comment] 2021-01-13 10:57
i cannot reproduce it not showing the activation key page on linux or windows. It might be fixed in the latest version.

**Comment by heapwolf** [comment] 2021-01-14 13:15
There is no "activation key page", that's a misnomer, there is an activation key input that is displayed when you have not yet entered your activation key. It is only required once, this is what @juliangruber entered. This UX is not optimized for download-all, but could be, let's explore that in a separate issue.

**Closed by heapwolf** 2021-01-14 13:15 UTC
Labels: bug, cannot-reproduce
